# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dSWS3XBhzjexAUUJhD1BG-g0T3uKTYO
"""

import hmac
import hashlib
import time
import requests
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/verify-keys', methods=['POST'])
def verify_keys():
    data = request.get_json()
    api_key = data.get('apiKey')
    api_secret = data.get('apiSecret')

    if not api_key or not api_secret:
        return jsonify({'success': False, 'message': 'Missing API Key or Secret'}), 400

    try:
        # Create the query string with timestamp
        timestamp = int(time.time() * 1000)
        query_string = f'timestamp={timestamp}'

        # Create the signature
        signature = hmac.new(
            api_secret.encode('utf-8'),
            query_string.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()

        # Make the request to Binance
        headers = {'X-MBX-APIKEY': api_key}
        url = f'https://api.binance.com/api/v3/account?{query_string}&signature={signature}'
        response = requests.get(url, headers=headers)

         if api_key == "test" and api_secret == "test":
        return jsonify({"success": True})
    else:
        return jsonify({"success": False})
